language: ruby
rvm:
 - 2.1.2
 - 2.0.0
notifications:
  hipchat:
    rooms:
      secure: TsK/bMZTm/izur4uaaJ0A8vJiY7929vyV2YgmyEMghlc8SxSdARKCubsbarTpc3kBMKexBPds4ve6BeRuC7iofRwKiRVJEqn7XFsOUXfeTiL+OS/f2Q5ydXQkrPpw6ELW84dSA/nrmhezVE7zMZoAy9jPourIAeBTxRynuYy9rw=
