language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1.2
      jdk: oraclejdk7
    - rvm: 2.1.2
      jdk: openjdk7
    - rvm: 2.1.2
      jdk: oraclejdk7
before_install:
  - gem update --system
  - gem --version
  - gem update bundler
  - gem list bundler
# services:
#   - mysql
#   - rabbitmq
# before_script:
#   - mysql -e 'create database myapp_test;'
